/**
 * THIS FILE IS AUTO-GENERATED by the RevenueCat Replit integration.
 *
 * To use the seed script:
 *   1. Connect the RevenueCat integration in Replit (it will overwrite this file).
 *   2. OR manually set REVENUECAT_SECRET_API_KEY and run: npx tsx scripts/seedRevenueCat.ts
 */
import { createClient, createConfig } from '@replit/revenuecat-sdk/dist/client';

export async function getUncachableRevenueCatClient() {
  const secretKey = process.env.REVENUECAT_SECRET_API_KEY;
  if (!secretKey) {
    throw new Error(
      'REVENUECAT_SECRET_API_KEY is not set.\n' +
        'Connect the RevenueCat integration in Replit, or set this env var manually.',
    );
  }

  const config = createConfig({
    baseUrl: 'https://api.revenuecat.com/v2',
    headers: { Authorization: `Bearer ${secretKey}` },
  });

  return createClient(config);
}
